import Link from "next/link";
import { asset } from "../lib/assets";

export default function ChiSiamoPage() {
  return <main className="about-page">
    <section className="about-hero"><img src={asset("/images/atelier/atelier.png")} alt="Atelier Unica Automobili"/><div className="about-shade"/><div className="about-title"><p>Bergamo · Italia</p><h1>Tre ragazzi.<br/>Un sogno ostinato.</h1><span>Costruire automobili impossibili da confondere.</span></div></section>
    <section className="about-manifesto" data-reveal><p className="section-tag">/ Chi siamo</p><div><h2>Una passione diventata<br/><em>progetto.</em></h2><p className="about-lead">Unica Automobili nasce a Bergamo dal sogno di tre ragazzi cresciuti con la stessa, incontenibile passione per le automobili.</p><div className="about-columns"><p>Non volevamo limitarci ad ammirare le grandi carrozzerie italiane. Volevamo raccoglierne lo spirito: partire da una meccanica eccezionale e avere il coraggio di immaginarla diversamente.</p><p>Il nome Unica è il nostro impegno. Ogni automobile deve esserlo nella forma, nel carattere e nel rapporto con la persona per cui viene costruita. Non una variante: un progetto irripetibile.</p></div></div></section>
    <section className="three-founders" data-reveal><p className="section-tag light">/ Tre fondatori</p><div><span>Tre sensibilità</span><i/><span>Una visione</span><i/><span>Unica Automobili</span></div><h2>La competenza si costruisce.<br/><em>La passione viene prima.</em></h2><p>Siamo presenti in ogni fase e siamo noi il primo contatto del cliente. Nessun filtro, nessuna distanza tra chi immagina l’automobile e chi la rende reale.</p></section>
    <section className="beliefs"><article data-reveal><span>01</span><h3>La forma segue<br/>il carattere.</h3><p>Non cerchiamo uno stile applicabile a tutto. Ogni progetto deve esprimere la meccanica e la personalità da cui nasce.</p></article><article data-reveal><span>02</span><h3>La tecnica è<br/>parte del design.</h3><p>Prestazioni, ergonomia e bellezza vengono sviluppate come un solo problema, non come discipline separate.</p></article><article data-reveal><span>03</span><h3>Il cliente è<br/>parte del progetto.</h3><p>Una Unica non si sceglie da un catalogo. Si costruisce attraverso un dialogo, fino all’ultimo dettaglio.</p></article></section>
    <section className="about-signature" data-reveal><div><p className="section-tag light">/ Il nostro nome</p><h2>Unica non è una promessa<br/>di esclusività.<br/><em>È un metodo di lavoro.</em></h2></div><Link href="/atelier/">Scopri come lavoriamo <span>↗</span></Link></section>
  </main>;
}
